import Feed from '@/components/main'

export const metadata = {
   title: 'Home Page | MetaBlog',
   description: 'Generated by create next app',
}


export default async function page() {
   return (
      <main className="container mx-auto">
         <Feed />
      </main>
   )
}
