import AuthorComponent from '@/components/author'

export const metadata = {
   title: 'Author Page | MetaBlog',
   description: 'Generated by create next app',
}

const Author = () => {
   return (
      <main>
         <AuthorComponent />
      </main>
   )
}

export default Author
