"use client"
import AuthorComponent from '@/components/author'

export const metadata = {
   title: 'Author | NextBlog',
   description: 'Generated by create next app',
}

const Page = () => {
   return (
      <main>
         <AuthorComponent />
      </main>
   )
}

export default Page
