import React from 'react'
import Explore from '@/components/explore'

export const metadata = {
    title: 'Blog Page | MetaBlog',
    description: 'Generated by create next app',
}

const page = () => {
    return (
        <main>
            <Explore />
        </main>
    )
}

export default page
