import Explore from '@/components/explore'

export const metadata = {
    title: 'Blog | NextBlog',
    description: 'Generated by create next app',
}

export const fetchCache = 'force-no-store';

const page = () => {
    return (
        <main>
            <Explore />
        </main>
    )
}

export default page
